name = "birl"
version = "1.9.0"

description = "Date / Time handling for Gleam"
gleam = ">= 0.32.0"
internal_modules = ["birl/zones"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "massivefermion", repo = "birl" }
links = [{ title = "Gleam", href = "https://gleam.run" }]

[dependencies]
ranger = ">= 1.4.0 and < 2.0.0"
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
